### ISSUE TITLE
想从头训练一个人，audio2face需要重新训练吗

### ISSUE THREAD

**Issue by zhanchao019** [zhangchenxu528/FACIAL#10]
其他几个模块好像都有训练代码啥的，不太清楚audio2face这个模块在训练一个新的形象的时候需不需要改变呢？ 这个模块的作用我的理解是提供了head pose和expression向量,那如果直接写死这两个值是不是整体网络功能仍然可用呢

**Comment by zhangchenxu528** [comment]
你好，这部分内容训练内容还没有上传。我会在本月整理一个从头训练一个人的colab demo，使用一个新人物的2-3分钟视频来完成所有训练。

**Comment by h310558606** [comment]
每天过来看一遍有没有更新

**Comment by zhanchao019** [comment]
每日观察～ 还好懒癌发作不想自己写代码训

**Comment by kunyao2015** [comment]
每日观察 +1

**Comment by CruiseYuGH** [comment]
每日观察 +1

**Comment by h310558606** [comment]
观察无果

**Comment by jennysunny** [comment]
每日检查+1

**Comment by rebotnix** [comment]
如果我们能理解并学习如何训练自己的图像，我也会非常高兴。我利用推论在Nvidia公司的节能型Jetson设备上运行。另外，杰特森上的引擎目前正在将这段文字从德语翻译成中文。问题是，我们是否可以在html5页面上开发多语言模型。我希望你能理解我基于NLP的翻译。我期待着你的答复。

**Comment by h310558606** [comment]
为何还是没有更新呢

**Comment by rebotnix** [comment]
我想作者是相当忙碌的。

**Comment by zhangchenxu528** [comment]
Thanks for your attention, I have updated the new demo.

**Comment by zhanchao019** [comment]
> 

非常感谢你的贡献，晚上就开始follow工作
