### ISSUE TITLE
关于train3.npz文件中的结构

### ISSUE THREAD

**Issue by Linxu59** [zhangchenxu528/FACIAL#12]
作者你好，我想请教一下。这个train3.npz是怎么生成的？有相应的源码吗？想知道这个文件保存了哪些参数。是不是就是你用微软的那个Deep3DFaceReconstruction对输入的视频每一帧进行重建，然后将相应的参数保存到npz文件中？但是我看代码，好像不止identify、texture和lighting这些参数。

**Comment by zhangchenxu528** [comment]
我对Reconstruction结果还进行了处理。这里面添加了eye blink等信息。很抱歉对大家造成了困扰，我会尽快添加数据处理部分代码。

**Comment by zhangchenxu528** [comment]
請參考新的demo，裏面有數據處理部分。
