### ISSUE TITLE
About the step one training in the paper

### ISSUE THREAD

**Issue by ken-ouyang** [zhangchenxu528/FACIAL#13]
Hi, thanks for sharing the excellent work! 

I have a question regarding the details of the paper.  There is a step one training adopted on the whole dataset which is to learn a general mapping between the audio and the attributes. I wonder how much this step contributes to the final performance. For example, if I directly train a personalized video, would the performance degrade much? What if I have a longer video such as 15 minutes talking face?  

Thanks very much!

**Comment by zhangchenxu528** [comment]
If you only have a short video (2-3 mins), you need to finetune prev net. For 15 mins video, I think it is enough to train from scratch.
