### ISSUE TITLE
How to run the code locally?

### ISSUE THREAD

**Issue by sd707589** [zhangchenxu528/FACIAL#14]
Hi, I noticed in the instruction there were only examples running on Google Colab. There exists some difference between Colab and local PC, such as the pretrained models and other wheels. 

Could you add some details on how to set up the local runtime? 

Very appreciated!

**Comment by zhanchao019** [comment]
I'm planning to write the local process on my fork this weekend. u can pay attention to it

**Comment by sd707589** [comment]
> I'm planning to write the local process on my fork this weekend. u can pay attention to it

Great!  By the way, could you add a demo video for a quick look?

**Comment by zhangchenxu528** [comment]
Since I configured Colab directly according to my local machine, I don't think there is any big difference between local running and Colab for Facial code.

@zhanchao019 If you finished, please leave a message to me, and I will update the Readme according to your instruction. Thanks a lot.
