### ISSUE TITLE
KeyError: 'meanshape'

### ISSUE THREAD

**Issue by Liuxiaoan1** [zhangchenxu528/FACIAL#15]
我下了BFM09，并且把face05_4seg.mat改成BFM_model_front.mat，face05_4seg.txt改成std_exp.txt放到BFM文件夹中，但是还是报错 File "fit_headpose.py", line 24, in <module>
    facemodel = BFM()
  File "/home/ubuntu/FACIAL-main/face_render/load_data.py", line 12, in __init__
    self.meanshape = model['meanshape'] # mean face shape 
KeyError: 'meanshape'
是指模型中没有这个键值，请问作者遇到过这个问题吗？该怎么解决呢？

**Comment by zhangchenxu528** [comment]
Deep3Dfacereconstruction中使用的是处理过的文件。请参考：https://github.com/microsoft/Deep3DFaceReconstruction。
其中 utils.py 中有生成BFM_model_front.mat的transfer代码。我的建议是跑一遍Deep3DFaceReconstruction的demo，你就会得到需要的全部文件。

**Comment by Liuxiaoan1** [comment]
哇！谢谢！解决啦

**Comment by hello3932** [comment]
@Liuxiaoan1 
Hello, how did you solve this problem?
