### ISSUE TITLE
How to train a custom latest_net_G.pth

### ISSUE THREAD

**Issue by icklerly1** [zhangchenxu528/FACIAL#16]
Hi there, 
I tested your avatars "test1" and "obama2" in parallel. 
I noticed that at the very last step face2video (test_video.py) you load a model called "latest_net_G.pth". This model seems to be responsible for the background. Unfortunately you do not describe how to train that "latest_net_G.pth" in your colab.

Would it be possible to train a custom "latest_net_G.pth". And if yes, could you please provide the code for that?

Thanks in advance!

**Comment by zhangchenxu528** [comment]
The training code has also been uploaded to Github, and I will also add a training explanation in Colab Demo.
