### ISSUE TITLE
how to get the train data by using my video（train1_openface/, Openface result.）

### ISSUE THREAD

**Issue by CruiseYuGH** [zhangchenxu528/FACIAL#17]

**Comment by MingZJU** [comment]
Thanks for your sharing @zhangchenxu528 !

I have the same question about openface, as I cann't obtain the same csv file as the one in our colab.

Maybe you can give some advice, thank you~

**Comment by zhangchenxu528** [comment]
I used 512*512 resized video when running Openface. Here is the video link: https://drive.google.com/file/d/1h7iHCTVt9whBaLocK1KhONo6lYAPNb8I/view?usp=sharing

Some openface commands:
cd ./OpenFace/build
./bin/FeatureExtraction -f 'train1_512_audio.mkv' -out_dir  'train1_openface/'

**Comment by MingZJU** [comment]
@zhangchenxu528 It works, many thanks!

**Comment by psuu0001** [comment]
> @zhangchenxu528 It works, many thanks!

Do you know how to build the same csv file now? Could you please show me the link of openface? I can't find a openface github project which contains ./OpenFace/build.
