### ISSUE TITLE
How to train my own data？

### ISSUE THREAD

**Issue by CruiseYuGH** [zhangchenxu528/FACIAL#18]
Thanks for your sharing @zhangchenxu528 。
I get  the bad results by using my own data, the results seems to be affected by "latest_net_G.pth".
How to train a custom latest_net_G.pth? Or do I need to do some other work?
![000700](https://user-images.githubusercontent.com/31302028/147535527-0e96d8cf-2280-4343-a0b5-417bf0573c07.jpg)
.

**Comment by Liuxiaoan1** [comment]
我也遇到了同样的问题，期待作者的答复，如何生成自己的‘latest_net_G.pth’

**Comment by MingZJU** [comment]
Turn to FACIAL/face2vid/train.py and FACIAL/face2vid/tip.md.

**Comment by Liuxiaoan1** [comment]
I've tried train.py, but I can't find ‘modelL1_F-1-weight.t7’ and ‘modelL1_F-1-bias.t7’

**Comment by MingZJU** [comment]
> I've tried train.py, but I can't find ‘modelL1_F-1-weight.t7’ and ‘modelL1_F-1-bias.t7’

The author said "Rendering-to-video module borrows heavily from everybody-dance-now". 

You can go to https://github.com/Lotayou/everybody_dance_now_pytorch/tree/master/models, and copy "spynet_models" to face2vid/models/

**Comment by Liuxiaoan1** [comment]
> > I've tried train.py, but I can't find ‘modelL1_F-1-weight.t7’ and ‘modelL1_F-1-bias.t7’
> 
> The author said "Rendering-to-video module borrows heavily from everybody-dance-now".
> 
> You can go to https://github.com/Lotayou/everybody_dance_now_pytorch/tree/master/models, and copy "spynet_models" to face2vid/models/

Thanks！

**Comment by MingZJU** [comment]
But I wonder the work of train3 in training cloab. And which datasets should be used to train our own latest_net_G.pth? @zhangchenxu528

**Comment by lshil00** [comment]
> But I’m a little confused with train3 in training cloab. And which datasets should be used to train our own latest_net_G.pth? @zhangchenxu528
> 
> Solved.

Hi, have you solved this problem?

**Comment by zhangchenxu528** [comment]
We did not use spynet_models, I deleted this content in the updated code. Thanks for discovering this problem.

BTW, I have added the training part to the Colab demo, hope it could be helpful to your training.

**Comment by zhangchenxu528** [comment]
@lshil00 The dataset includes rendered 3D faces and real images. Please refer to the Colab link for details.

**Comment by psuu0001** [comment]
> @lshil00 The dataset includes rendered 3D faces and real images. Please refer to the Colab link for details.

Awesome! Thanks for your work!
