### ISSUE TITLE
The supplementary file of this paper.

### ISSUE THREAD

**Issue by LeoniusChen** [zhangchenxu528/FACIAL#19]
Hi, I read your paper. Excellet work! I wonder where I can find the supplementary file of your paper, since there are more details in it. Thanks~

**Comment by zhao1f** [comment]
Hi， I think you could find more details on the official website of the ICCV conference [here].(https://openaccess.thecvf.com/content/ICCV2021/html/Zhang_FACIAL_Synthesizing_Dynamic_Talking_Face_With_Implicit_Attribute_Learning_ICCV_2021_paper.html)

**Comment by zhangchenxu528** [comment]
Thanks for your attention. You can also get supplementary files from our website.
https://personal.utdallas.edu/~xguo/

**Comment by LeoniusChen** [comment]
Thanks for your kind help ~
