### ISSUE TITLE
Colab demo not running?

### ISSUE THREAD

**Issue by RAJA-PARIKSHAT** [zhangchenxu528/FACIAL#21]
I was running collab demo but in the examples folder there was no test_images folder, so I can't run the collab demo, and if I run demo on my own audio file and image, how can I do it? @zhangchenxu528

**Comment by zhangchenxu528** [comment]
Can you tell me which part of the report is wrong?

In my understanding, you need to get three files: 
output_graph.pb, (https://github.com/mozilla/DeepSpeech/releases/tag/v0.1.0)
BFM_model_front.mat, and std_exp.txt.  #15 #4 

There should be no problems with the other parts.

**Comment by RAJA-PARIKSHAT** [comment]
@zhangchenxu528 I cannot find the std_exp.txt and bfm_model_front.mat files. Also if I want to train on a custom video, first I have to preprocess it?
