### ISSUE TITLE
How to create the "train1_openface" file?

### ISSUE THREAD

**Issue by lshil00** [zhangchenxu528/FACIAL#23]
Hi, I am a little confused about the Openface file. 
Is it related to the Deep3DFaceReconstruction files? Then how can I create the csv file?
Looking forward to your reply.Thanks!

**Comment by zhangchenxu528** [comment]
We also used the blink AU value from Openface.
For CSV file generation, please see #17.

**Comment by lshil00** [comment]
> We also used the blink AU value from Openface. For CSV file generation, please see #17.

Actually I have already seen this issue... but still haven't understood yet. How could I find the "/Openface/" folder? Is it in another repo?
Great thanks! 
> Some openface commands:
> cd ./OpenFace/build
> ./bin/FeatureExtraction -f 'train1_512_audio.mkv' -out_dir 'train1_openface/'

**Comment by zhangchenxu528** [comment]
For Openface, please refer to their repo: https://github.com/TadasBaltrusaitis/OpenFace.

**Comment by lshil00** [comment]
> For Openface, please refer to their repo: https://github.com/TadasBaltrusaitis/OpenFace.

Thanks for your kind reply! The problem has been solved.
