### ISSUE TITLE
Audio/Video Sync Problem

### ISSUE THREAD

**Issue by MingZJU** [zhangchenxu528/FACIAL#24]
Hi guys ,

I've already synthesized my own video, and the resolution seems good!
However, the voice sometimes not sync well with the video (I used mandarin tts speech).

https://user-images.githubusercontent.com/53510802/149249264-89a4c5cb-5ef7-49f7-ba87-c999e7a8470c.mp4

Does anyone ever have similar problem? Any suggestion is appreciated.

Thanks a lot

**Comment by zhangchenxu528** [comment]
Since my basic training is English, for Chinese, I suggest you try to increase the training data and the results should improve.

**Comment by MingZJU** [comment]
I realized it. Do you think it also relates to the deepspeech model? It was trained on English dataset.

**Comment by zhangchenxu528** [comment]
I think deep speech will have an impact since its features are alphabet probability values. You can try using MFCC features.

**Comment by MingZJU** [comment]
Thanks. I will share my training results as soon as finished.

**Comment by lshil00** [comment]
Hi, I also tried to create my own video following the instructions, but got really poor results. 
I use a 3-min video for training and 10-sec audio for testing. Is there any suggestions you and the author @zhangchenxu528  could provide? Great thanks

https://user-images.githubusercontent.com/47272107/150925055-b35547c5-fcd6-44df-94b6-01c43e7d7577.mp4

**Comment by zhangchenxu528** [comment]
@lshil00  It seems the face2video network was not fully trained. Did you train it with 50 epochs?

**Comment by lshil00** [comment]
> @lshil00 It seems the face2video network was not fully trained. Did you train it with 50 epochs?

Yes, I trained it with 50 epochs.

**Comment by MingZJU** [comment]
> > @lshil00 It seems the face2video network was not fully trained. Did you train it with 50 epochs?
> 
> Yes, I trained it with 50 epochs.

You may also try Gen_50.mdl.

**Comment by lshil00** [comment]
> 

Ok, I will try it ASAP.Thanks!

**Comment by yaleimeng** [comment]
I have tried using the 26-d MFCC features instead of 29-d alphabet probabilities to train audio2fance model， but get a worse result video.
This is not a better way.

**Comment by MingZJU** [comment]
I used a mandarin model in deepspeech0.9.2 to train Gen.mdl. Results still have severe sync problem, I am trying to solve it.

**Comment by sd707589** [comment]
@lshil00 @MingZJU Hi guys, have you gotten any progress? I am facing the same problem as you now.

**Comment by MingZJU** [comment]
I may try it in later days.

**Comment by kunyao2015** [comment]
Are There any solutions to solve sync problem? @MingZJU
