### ISSUE TITLE
Something wrong with .mat file

### ISSUE THREAD

**Issue by lshil00** [zhangchenxu528/FACIAL#26]
I used 512*512 resized video when running Openface. Here is the video link: https://drive.google.com/file/d/1h7iHCTVt9whBaLocK1KhONo6lYAPNb8I/view?usp=sharing

Some openface commands:
cd ./OpenFace/build
./bin/FeatureExtraction -f 'train1_512_audio.mkv' -out_dir  'train1_openface/'

_Originally posted by @zhangchenxu528 in https://github.com/zhangchenxu528/FACIAL/issues/17#issuecomment-1000945373_

**Comment by lshil00** [comment]
Hi, sorry to bother you again, but I have run the code and created the mat file as expected. However, I found that the values of my coefficients aren't the same as yours in "video_preprocess/train1_deep3Dface" . Could you please tell me is there anything wrong? Great thanks!
BTW, I use the result from OpenFace to create the 5 facial landmarks for Deep3DFaceReconstruction.

**Comment by zhangchenxu528** [comment]
Since the version I am using is from 2 years ago, it may be a little different from yours. But the meaning for each value is same. 
id_coeff = coeff[:,:80]
ex_coeff = coeff[:,80:144]
tex_coeff = coeff[:,144:224]
angles = coeff[:,224:227]
gamma = coeff[:,227:254]
translation = coeff[:,254:257]

**Comment by geek0075** [comment]
Good. Thanks!
