### ISSUE TITLE
Whats the standard of training dataset?

### ISSUE THREAD

**Issue by psuu0001** [zhangchenxu528/FACIAL#27]
Hi, I have read your paper. It's a good idea to use 3d construction to do aud2face task. I plan to make my own Chinese speech dataset but I don't know how what's the standard of making a dataset. Your paper mentioned that you used 450 clips for training. I want to know will the background music allowed in video clips or just one person is talking?

**Comment by zhangchenxu528** [comment]
In our dataset, there is only one person during the speech. I recommend at least half an hour of data for general training.

**Comment by psuu0001** [comment]
> In our dataset, there is only one person during the speech. I recommend at least half an hour of data for general training.

Is background music allowed in video?

**Comment by MingZJU** [comment]
Along this question, I think the general model (Gen*.mdl) should cover most mandarin speech, so that it can handle different inputs.
Maybe a large dataset, roughly as many as 450 clips, is much more better.

Is it right? Do I misunderstand it? @zhangchenxu528

**Comment by zhangchenxu528** [comment]
@psuu0001  I think the music will affect the quality of audio mouth sync.

**Comment by zhangchenxu528** [comment]
@MingZJU Yes, you are right.
