### ISSUE TITLE
What kind of GPU is required

### ISSUE THREAD

**Issue by ZziTaiLeo** [zhangchenxu528/FACIAL#29]
May I ask what type of GPU you are using, and how long does the whole training process take.

**Comment by zhangchenxu528** [comment]
We use 1080 ti. 
For audio2face, it takes less than 5 hours for training. 
For face2vid, it takes ~10 hours for training.

**Comment by DmitriyVahrushev** [comment]
Hello, @zhangchenxu528 ! Do you mean it takes around 15 hours to train the model on a dataset consisting of 450 clips? Or does it take 15 hours to finetune the model on a new person?
