### ISSUE TITLE
how to get .npz file like obama2.npz?

### ISSUE THREAD

**Issue by kelisiya** [zhangchenxu528/FACIAL#3]

**Comment by 821029883** [comment]
1. Use audio2face/audio_ Preprocessing.py convert your audio to audio feature (. Pkl as suffix)
2. Use audioface/test.py to convert audio feature to pose param (. Npz as suffix)

**Comment by kelisiya** [comment]
> 1. Use audio2face/audio_ Preprocessing.py convert your audio to audio feature (. Pkl as suffix)
> 2. Use audioface/test.py to convert audio feature to pose param (. Npz as suffix)

Thanks for reply , I solved it . But I have two new problems , what means train3.npz and if I want to use my image as input , how to render it in your code?
