### ISSUE TITLE
Where from find the output_graph.pb file?

### ISSUE THREAD

**Issue by muxiddin19** [zhangchenxu528/FACIAL#30]
!cp /content/gdrive/MyDrive/FACIAL/output_graph.pb /content/FACIAL/audio2face/ds_graph/output_graph.pb

cp: cannot stat '/content/gdrive/MyDrive/FACIAL/output_graph.pb': No such file or directory

**Comment by yaleimeng** [comment]
in the  facial_demo.ipynb, last cell of section 2---Install requirements :
### Please download the pre-trained DeepSpeech model v0.1.0 from Mozilla (hhttps://github.com/mozilla/DeepSpeech/releases/tag/v0.1.0) and place it in /content/FACIAL/audio2face/ds_graph.

Unfortunately, downloading files from github is very slow and unstable in China mainland. This is  another [download link](https://www.123pan.com/s/qvT9-2xnPH) shared by me。

**Comment by yaleimeng** [comment]
in the  facial_demo.ipynb, last cell of section 2---Install requirements :
### Please download the pre-trained DeepSpeech model v0.1.0 from Mozilla (hhttps://github.com/mozilla/DeepSpeech/releases/tag/v0.1.0) and place it in /content/FACIAL/audio2face/ds_graph.

Unfortunately, downloading files from github is very slow and unstable in China mainland. This is  another [download link](https://www.123pan.com/s/qvT9-2xnPH) shared by me。

**Comment by zhangchenxu528** [comment]
This issue has been resolved, please try again.
