### ISSUE TITLE
Puzzle of train our custom dataset encountered

### ISSUE THREAD

**Issue by xiao-keeplearning** [zhangchenxu528/FACIAL#33]
Hi, thank your awesome work! 
I try to use your method to train the custom dataset, but the video fps of trainet is 25. I don’t want to force frame rate of those videos to to 30. Can I achieve this by modifying the original code?

https://github.com/zhangchenxu528/FACIAL/blob/95eaf8f40e44e8c1ad5ed047b874881fb6115b66/audio2face/audio_preprocessing.py#L41
Do I need to change only this line of code? Looking forward to your advice.

**Comment by yaleimeng** [comment]
应该是可以支持的。音频信号默认是50帧/s，当视频画面25帧/s时，声音直接隔帧采样就行了。这样能保证声音与画面的时间对齐。
不过代码里面涉及帧率fps=30的地方比较多，需要注意每一个环节。

**Comment by xiao-keeplearning** [comment]
非常感谢您的回复，我想再确认下，您说的隔帧采样是不是以下音频处理代码：
https://github.com/zhangchenxu528/FACIAL/blob/95eaf8f40e44e8c1ad5ed047b874881fb6115b66/audio2face/_utils/audio_handler.py#L143-L144
`audio_window_stride`设置为2

**Comment by zhangchenxu528** [comment]
@xiao-keeplearning  

1）您好，如果是25 fps 的话，处理语音feature时可以将audio_window_stride设置为2。此外你还需要在处理每一帧video数据时使用25 fps，以及最后合成video的时候使用25 fps。

2）当然一个简单的方法是使用 ffmpeg 把视频转成30 fps。Eg: ffmpeg -i input.mp4  -r 30 -b 5M  -y out.mp4

**Comment by xiao-keeplearning** [comment]
Thanks!

**Comment by yaleimeng** [comment]
我已经使用25帧/s的视频完成了整个训练和预测流程，是没有问题的。
整体保持25帧/s的好处在于导出图像时不需要插值，跟原视频完全一致，而且声音帧特征不需要线性插值，减少信息损失。
另外似乎训练视频并不是仅支持512×512的分辨率（比如700×700），我之前以为不行，都先降低了之后再开始处理的。

**Comment by zhangchenxu528** [comment]
@yaleimeng  训练视频是支持其他分辨率的。但请注意pose2vid中有些奇怪的分辨率会报错，需要稍作修改。
