### ISSUE TITLE
train body parts (say hands)

### ISSUE THREAD

**Issue by MingZJU** [zhangchenxu528/FACIAL#34]
Is it possible to train the model with video that contains body action, other than only head?

Can anybody give some advice?

Thanks.

**Comment by trivikramak** [comment]
Hi,
Any updates on this?

**Comment by zhangchenxu528** [comment]
Sure, you can do it. 

In fact, we also did some work with the full-body generation. We hope our code can be released as soon as possible this year.

**Comment by trivikramak** [comment]
Great to hear, looking forward to it!

**Comment by rohaantahir** [comment]
Hi @zhangchenxu528 very nice work. I am currently working on your repo and wanted to ask if the above mentioned problem has been resolved. I wanted to recreate the video that has some hand movement as well. can you please tell how to do it?
