### ISSUE TITLE
有关中文语音驱动的嘴型不对齐问题

### ISSUE THREAD

**Issue by DATOULEE** [zhangchenxu528/FACIAL#35]
用中文数据fine-tune的FACIAL-GAN嘴型不对齐，是否针对中文场景，需要重新训练FACIAL-GAN这部分？

**Comment by yaleimeng** [comment]
其实英文视频同样对不齐，只是没那么明显，仔细看是能看出来的。
我想应该是它的audio2face模块存在不足，需要改进。

**Comment by kunyao2015** [comment]
> 其实英文视频同样对不齐，只是没那么明显，仔细看是能看出来的。 我想应该是它的audio2face模块存在不足，需要改进。

@yaleimeng 你好， 中文唇音对齐，你的结果现在有变好吗

**Comment by yaleimeng** [comment]
@kunyao2015 很遗憾，暂时没有找到改善的办法。目前是在看同一领域的其他研究工作，看有没有能直接用的，或者有模块能组合搭配的。

**Comment by kunyao2015** [comment]
@yaleimeng 我同样尝试了 NVP(FACIAL文中对比的方法) ， 也很难同步， 或许是基于3DMM方法就存在的缺陷？ 我不确定， wav2lip 就能很好的对齐， 有啥思路可以交流交流

**Comment by zhangchenxu528** [comment]
我最近对中文进行了尝试，发现中文效果确实不好。我认为重要原因是Deepspeech特征和中文不匹配。如果是想要合成中文说话数据，我建议尝试其他的方法。

**Comment by yaleimeng** [comment]
@kunyao2015 是啊。能达到wav2lip的程度也算能接受了。。我做了一个魔改：就是在FACIAL生成完之后再跑一遍wav2lip，虽然处理时间会更长，而且局部也有轻微模糊和瑕疵，但同步性强多了。

**Comment by kunyao2015** [comment]
@zhangchenxu528  deepspeech 换成0.9.3版本的中文256维特征， 同步效果也没改善 ，loss已经降的很低了，有些费解

**Comment by LangR7** [comment]
> @zhangchenxu528 deepspeech 换成0.9.3版本的中文256维特征， 同步效果也没改善 ，loss已经降的很低了，有些费解

你好，能问问您“deepspeech 换成0.9.3版本的中文256维特征”您用的是.pb的frozen模型吗？哪里可以找到这个模型，谢谢

**Comment by yaleimeng** [comment]
@LangR7   模型就在[官方发布链接](https://github.com/mozilla/DeepSpeech/releases/tag/v0.9.3)下载啊。只是用起来需要在facial里面修改一些东西。

**Comment by wzx7084** [comment]
> 
你好，请问您知道deepspeech 093 pbmm模型文件怎么导入吗？

**Comment by wzx7084** [comment]
@yaleimeng 你好，请问你知道deepapeech 093 pbmm文件具体怎么导入吗？

**Comment by yaleimeng** [comment]
实验效果不好，需要在处理完之后再加一个口型同步才行。
时间过去太久，以前的项目文件也在重装系统时不慎擦除了。不过你可以参考以往issue里面提到的一些思路。
