### ISSUE TITLE
有关于Gtem，为啥用了UnetSkipConnectionBlock 网络？

### ISSUE THREAD

**Issue by CruiseYuGH** [zhangchenxu528/FACIAL#36]
作者您好，感谢您做了这么棒的一个工作。但是目前再查看相关代码的时候有个问题想咨询您。有关于有关于Gtem，为啥用了UnetSkipConnectionBlock 网络？不知道这一块的目的是啥？
其次的话，与唇形强相关的lossg_e 不知道您训练到多少能有较好的同步率。

**Comment by zhangchenxu528** [comment]
你好， 抱歉最近有些事情耽搁了没及时回复。

1）这里 UnetSkipConnectionBlock 网络主要作用是增强Gtem的学习能力，特别是training 数据很多的时候。不过一般情况你可以不用添加UnetSkipConnectionBlock网络。

2）lossg_e 我一般20 epochs 左右开始看到比较好的结果。
