### ISSUE TITLE
No accurate output for custom video.

### ISSUE THREAD

**Issue by TejaswiniiB** [zhangchenxu528/FACIAL#38]
Hi @zhangchenxu528 , 
Thankyou for the wonderful project ! Looked at your demo video and output (for even higher resolution) in colab. 
I have trained for custom video model using your training colab notebook. Don't know why, but didnt get proper output video for a custom video of 4 mins. 
Except the preprocessed data, rest of everything I used, is same as provided in the colab notebook.

**Comment by zhangchenxu528** [comment]
Can you show some examples?  And How many frames are used in face2video training?

**Comment by TejaswiniiB** [comment]
Hi @zhangchenxu528 ,
[Here is the link](https://drive.google.com/file/d/1JLf8qS4vEBAuGjhKzlGSP-sTyFBRwZaI/view?usp=sharing) for video_preprocess.zip, which contains 
- train1.mp4 - video of 4 mins length used for training
- test1.wav - audio used for testing
- And preprocessed data used

Since video is of 30 fps, total number of frames ~ `30*4*60` = 7200 frames

[Here](https://user-images.githubusercontent.com/24452276/158044569-0c85da69-ccae-4484-8cf4-8a573d6a4bd8.mp4) is the output video for input test audio after **50 epochs**
Here is the [loss_log.txt](https://github.com/zhangchenxu528/FACIAL/files/8238947/loss_log.txt).

Can you tell what can be done to improve the results, to get similar to the girl video you have trained on as sample?
Thankyou..
.

**Comment by shuntos** [comment]
@TejaswiniiB Could you share the resources to generate train1_512_audio.csv from frames?

**Comment by TejaswiniiB** [comment]
As mentioned in colab, generated it with Openface.
Followed the instructions from [here](https://github.com/TadasBaltrusaitis/OpenFace/wiki/Windows-Installation)
@shuntos

**Comment by zhangchenxu528** [comment]
@TejaswiniiB I noticed abnormal jumps in the final video. Please check the rendering_gaosi file, I think it is the head unnormalize error, you need to modify the --train_params_path parameter instead of using the original Obama's parameter.
