### ISSUE TITLE
file not exist

### ISSUE THREAD

**Issue by h310558606** [zhangchenxu528/FACIAL#4]
When I run the demo,I met the error below.
The file '/content/gdrive/MyDrive/FACIAL/BFM_model_front.mat'm does not exist.

cp: cannot stat '/content/gdrive/MyDrive/FACIAL/BFM_model_front.mat': No such file or directory
cp: cannot stat '/content/gdrive/MyDrive/FACIAL/std_exp.txt': No such file or directory

**Comment by zhangchenxu528** [comment]
Please run the demo of Deep3DFaceReconstruction first. You will find those generated files.
