### ISSUE TITLE
KeyError: "The name 'deepspeech/input_node:0' refers to a Tensor which does not exist. The operation, 'deepspeech/input_node', does not exist in the graph."

### ISSUE THREAD

**Issue by muxiddin19** [zhangchenxu528/FACIAL#40]
When I ran the python audio_preprocessing.py, I faced the problem. I use a Linux server container, and there was no TensorFlow 1.x available, so I used TensorFlow 2.8. Any solutions, please?

**Comment by RAJA-PARIKSHAT** [comment]
@muxiddin19 did you solve it?

**Comment by zhangchenxu528** [comment]
I only tested on TensorFlow 1.x and can't offer any suggestions.
