### ISSUE TITLE
ValueError: Input signal length=2 is too small to resample from 44100->16000`

### ISSUE THREAD

**Issue by TejaswiniiB** [zhangchenxu528/FACIAL#41]
Hi @zhangchenxu528 ,

Thank you for your wonderful project, with outputs so good on HD videos also ! 
I am trying to train on a 4 mins video for custom model (similar to the example you have provided in the train colab notebook). The [test audio](https://drive.google.com/file/d/1fbQseHgDvTdc_igKAMXa_7oj7ULGVMhp/view?usp=sharing) is of 28 secs duration.
But I am getting this error `ValueError: Input signal length=2 is too small to resample from 44100->16000` when running `python audio_preprocessing.py` , in the line 122 of `audio2face/_utils/audio_handler.py`. 

Then I replaced the line 120 in `audio2face/_utils/audio_handler.py` to `audio_sample = audio[subj][seq]['audio'].T` , by appending transpose. Then it ran properly only.

But `test1.npz ` is containing empty numpy array, after running `python test.py --audiopath /content/FACIAL/examples/audio_preprocessed/test1.pkl --checkpath /content/FACIAL/audio2face/checkpoint/train1/Gen-10.mdl` . 
Since test1.npz is empty, I am getting the below error when `python rendering_gaosi.py --train_params_path /content/FACIAL/video_preprocess/train1_posenew.npz --net_params_path ../examples/test-result/test1.npz` command is run.

```
  File "rendering_gaosi.py", line 153, in <module>
    netparams = savgol_filter(netparams, 7, 3, axis=0)
  File "/usr/local/lib/python3.7/dist-packages/scipy/signal/_savitzky_golay.py", line 337, in savgol_filter
    raise ValueError("If mode is 'interp', window_length must be less "
ValueError: If mode is 'interp', window_length must be less than or equal to the size of x.
```

I don't know if the latter error(test1.npz being empty) is because of the transpose part I added before.  Can you tell me how to overcome both these errors? Here is the [test audio](https://drive.google.com/file/d/1fbQseHgDvTdc_igKAMXa_7oj7ULGVMhp/view?usp=sharing) I used, for which it is not preprocessing properly..

**Comment by TejaswiniiB** [comment]
Hi,
Resolved the issue.
There were 2 channels in my test1.wav. So when it was read with scipy.io.wavefile.read , the output was 2D numpy array instead of 1D, due to which the initial error was generated. It got resolved by generating single channel test1.wav using ffmpeg.

**Comment by RAJA-PARIKSHAT** [comment]
@TejaswiniiB can you please describe in detail how you did? Actually, I am facing the same error and don't know how to resolve it.

**Comment by wsywsywsywsywsy979** [comment]
> @TejaswiniiB can you please describe in detail how you did? Actually, I am facing the same error and don't know how to resolve it.

hi, I have solved this problem , maybe my solution can help you, the following is my code: 
`# src_sig,sr = sf.read(old_file) ValueError: Input signal length=2 is too small to resample from 48000->16000
    src_sig,sr=librosa.load(old_file)
    src_sig=librosa.to_mono(src_sig) # change to mono
    dst_sig = librosa.resample(src_sig,sr,16000) `
just use "librosa" to load the stereo file intead of using "soundfile", and transform to mono.
