### ISSUE TITLE
Duration for training

### ISSUE THREAD

**Issue by TejaswiniiB** [zhangchenxu528/FACIAL#42]
Hi @zhangchenxu528 
I'm trying to run training colab notebook for 4 mins of train input video in colab. It's getting disconnected in between, after running for ~5hrs. 
Can you tell how much time it would take for training on custom video? 
Like how much did take for training for the sample girl video you have used in colab?

**Comment by zhangchenxu528** [comment]
The effective training time in Colab cannot support the face2vid training. I used the local machine to train for ~10 hours to get the final results. The Colab demo is just an example of introducing our training process.
