### ISSUE TITLE
cp: cannot stat 'examples/rendering/test1': No such file or directory

### ISSUE THREAD

**Issue by muxiddin19** [zhangchenxu528/FACIAL#43]
I failed in part 4.2. Prepare training and testing data part where asked to run 
cp -r /content/FACIAL/examples/rendering/test1 /content/FACIAL/face2vid/datasets/train3/test_A
cp -r /content/FACIAL/examples/rendering/test1 /content/FACIAL/face2vid/datasets/train3/test_B. I do have neither a rendering folder nor test1. Please, can you give me the location to download the related ones?

**Comment by TejaswiniiB** [comment]
Hi @muxiddin19 ,
Rendering folder would be generated in the 4.1 step (Run 3D face rendering) mostly. Did 4.1 step , the `python rendering_gaosi.py` one run properly without any errors?

**Comment by muxiddin19** [comment]
Thanks for the reply! 4.1 step the python rendering_gaosi.py run without any errors, but the Rendering folder was not generated. What will you suggest?
