### ISSUE TITLE
基于obama的epoch20 fine-tuned的audio2face 模型存在嘴型较难对齐的问题

### ISSUE THREAD

**Issue by DATOULEE** [zhangchenxu528/FACIAL#45]
您好，在audio2face训练中，根据您提供的obama的epoch20，在此基础上fine-tuned，会出现嘴型较难对齐的问题，猜测是因为过拟的导致，能否提供基于450 video训练的模型作为pre-train，谢谢

**Comment by zhangchenxu528** [comment]
使用中文数据fine-tuning结果很差，我目前认为有几点可能原因：
1）DeepSpeech feature对中文不太适用
2）Deep3DfaceReconstruction嘴部结果不够精确，可以考虑使用DECA替代 https://github.com/YadiraF/DECA
3）我们网络单次输出128帧，可能需要增加训练数据

**Comment by yaleimeng** [comment]
@zhangchenxu528 关于第2点，怎样利用DECA替代Deep3DfaceReconstruction？ 后者的主要功能是对每帧图像输出了1个序号.mat文件，但怎样使用DECA输出对应的mat文件或者直接传递数据呢？

**Comment by yaleimeng** [comment]
@zhangchenxu528 关于第2点，怎样利用DECA替代Deep3DfaceReconstruction？ 后者的主要功能是对每帧图像输出了1个序号.mat文件，但怎样使用DECA输出对应的mat文件或者直接传递数据呢？
