### ISSUE TITLE
On the inconsistency between training results and test results

### ISSUE THREAD

**Issue by banhuML** [zhangchenxu528/FACIAL#51]

**Comment by zhangchenxu528** [comment]
I think you are incorrectly using Obama's information, which shouldn't be used in your testing. 
1) Please check the test_A file to make sure the texture of the rendered result is right, not from Obama. 
2) Please check whether the pre-trained network name in the face2vid module is the one you trained.

**Comment by banhuML** [comment]
> I think you are incorrectly using Obama's information, which shouldn't be used in your testing.
> 
> 1. Please check the test_A file to make sure the texture of the rendered result is right, not from Obama.
> 2. Please check whether the pre-trained network name in the face2vid module is the one you trained.

Thanks for your replay!
1. test_A are correct. They are indeed the results of the characters I trained.
2. You mean the path in my test.py? Does being able to produce the right results during training mean that there is no problem with training and I don't need to train again?
3. Can I use the verification part of train.py  to complete the test?

**Comment by banhuML** [comment]
> Hello, the above problem has been solved, but the video shakes abnormally left and right. Can you tell me the reason?
> 
>  202204132111.mp4
