### ISSUE TITLE
The number of speakers in the dataset for general training audio2face

### ISSUE THREAD

**Issue by vndinh** [zhangchenxu528/FACIAL#57]
Thanh you for your wonderful works, @zhangchenxu528.

In your paper, you mention that *The proposed dataset contains rich samples of **more than 450 video clips*** and *Each video clip in our dataset has a stable fixed camera and appropriate lighting, **with only one speaker** for stable face generation.*

I confuse about the number of speakers in your dataset. Is there only one individual speaker in the entire dataset (450 video clips)? Or are there several speakers in your dataset but only one in each video clips?

**Comment by zhangchenxu528** [comment]
There are several speakers in the dataset but only one speaker in each video clips.

**Comment by vndinh** [comment]
Thank you for your response.
