### ISSUE TITLE
Error when run 5.2 Test face2video part

### ISSUE THREAD

**Issue by muxiddin19** [zhangchenxu528/FACIAL#58]
Thanks for the great work! When I tried to run the Testing variant on my Linux GPU server on the 5.2 Test face2video part, I faced the problem with running code:

import ffmpeg

audio_path ='../examples/audio/obama2.wav'
video_new='../examples/test_image/obama2/test_1.avi'
output = '../examples/test_image/obama2/test_1_audio.avi'
output_mp4 = '../examples/test_image/obama2/test_1_audio.mp4'
!ffmpeg -i '$video_new' -i '$audio_path' -c copy '$output'
!ffmpeg -i '$output'  '$output_mp4'

File "f2a.py", line 7
    ffmpeg -i $video_new -i '$audio_path' -c copy '$output'
              ^
SyntaxError: invalid syntax

I searched for a solution, but I could not find one. Please can you give some tips for it?

**Comment by zhangchenxu528** [comment]
‘ffmpeg -i $video_new -i '$audio_path' -c copy '$output' ’ needs to be executed from the command line
