### ISSUE TITLE
How to use weights(.pth) other than 'latest'?

### ISSUE THREAD

**Issue by dongju923** [zhangchenxu528/FACIAL#60]
How to set training weights (.pth) in test_video.py with intermediate weights rather than 'latest' the value of --which_epoch parameter?

**Comment by zhangchenxu528** [comment]
For example, --which_epoch 10.

**Comment by dongju923** [comment]
Ah, Thank you so much!!
But Can I use other stored weights (.pth) other than epoch?
 For example, when there are Demo 1 and Demo 2, Can't I save the training weights of Demo 1 and the training weights of Demo 2, and test using each weight when needed?

**Comment by dongju923** [comment]
> For example, --which_epoch 10.

**Comment by dongju923** [comment]
> For example, --which_epoch 10.

Ah, Thank you so much!!
But Can I use other stored weights (.pth) other than epoch?
For example, when there are Demo 1 and Demo 2, Can't I save the training weights of Demo 1 and the training weights of Demo 2, and test using each weight when needed?

**Comment by dongju923** [comment]
> For example, --which_epoch 10.
@zhangchenxu528 

Ah, Thank you so much!!
But Can I use other stored weights (.pth) other than epoch?
For example, when there are Demo 1 and Demo 2, Can't I save the training weights of Demo 1 and the training weights of Demo 2, and test using each weight when needed?
