### ISSUE TITLE
3DFaceReconstruction with PyTorch .mat files have different keys from provided video_preprocess!

### ISSUE THREAD

**Issue by geek0075** [zhangchenxu528/FACIAL#61]
Hi. Hello to everyone at the repo! Much kudos to Professor @zhangchenxu528 for his great research. I just used a new video to generate a 3DFaceReconstruction with PyTorch (Original notebook used Tensorflow) as detailed here: 

https://github.com/sicxu/Deep3DFaceRecon_pytorch

The generated .mat file has different keys from the video_preprocess provided. For example when running the file, handle_netface.py, there is this line of code:

faceshape[i-1,:] = loadmat(os.path.join(param_folder,str(i)+'.mat'))['coeff'][0,:]

This means that the .mat file is expected to have the key 'coeff'! However the .mat from the PyTorch version only has the following keys: 'angle', 'exp', 'gamma', 'id', 'tex', and 'trans'. When one concats these keys, its dimensions become equal to that of the original required 'coeff' key.

Here is what I have done so far! However, I am not sure that the keys are concatenated in the correct order. 

    coeffs = np.concatenate((mat_contents['angle'][0],
                            mat_contents['exp'][0],
                            mat_contents['gamma'][0],
                            mat_contents['id'][0],
                            mat_contents['tex'][0],
                            mat_contents['trans'][0]

Can someone please confirm if this is the correct order?

I have attached the two mat files here. 1.mat.orig.zip contains the .mat file in video_preprocess that has a 'coeff' key. The file 1.mat.zip contains the .mat file that doesn't have a 'coeff' key, but rather the following keys: 'angle', 'exp', 'gamma', 'id', 'tex', and 'trans'.

[1.mat.orig.zip](https://github.com/zhangchenxu528/FACIAL/files/8586735/1.mat.orig.zip)
[1.mat.zip](https://github.com/zhangchenxu528/FACIAL/files/8586737/1.mat.zip)

**Comment by dongju923** [comment]
Hi, If you create a mat file here, there is a 'coeff' value!
https://github.com/microsoft/Deep3DFaceReconstruction

**Comment by zhangchenxu528** [comment]
I didn't run the new version. For the old version, please refer to #26 .

**Comment by geek0075** [comment]
Thanks Professor @zhangchenxu528 and @dongju923. That #26 issue referred to by the professor answers my question and confirms my guess. Thanks for the clarification!

**Comment by foocker** [comment]
> Thanks Professor @zhangchenxu528 and @dongju923. That #26 issue referred to by the professor answers my question and confirms my guess. Thanks for the clarification!
so, you have use the old one (Deep3DFaceReconstruction) and openface to get the video_process?

**Comment by geek0075** [comment]
I used the new one. Mapped it to the old one like is described here....

**Comment by foocker** [comment]
> I used the new one. Mapped it to the old one like is described here....

good. 
but soory, i have miss a new problem. when run inference  of Deep3DFaceRecon_pytorch, **ninja: build stopped: subcommand.  failed.**.  may some pacakge conflict. what's your env? cuda, pytorch, tensorflow in Deep3DFaceRecon_pytorch.. thx .
i use pytorch3d solved this problem, not nvidxxx package
