### ISSUE TITLE
请问怎么控制眨眼频率？？？？

### ISSUE THREAD

**Issue by 1234269** [zhangchenxu528/FACIAL#63]
很棒的工作！但我训练了一个新的视频，原始视频眨眼比较多，但是训练出来的结果几乎不眨眼， 尝试修改csv文件也没有什么作用，请问有什么思路能够使得训练结果更频繁的眨眼呢？

**Comment by zhangchenxu528** [comment]
如果想获得更加频繁的眨眼，可以尝试scale眨眼blink weights。乘一个系数。

**Comment by MYTHOFLEGEND** [comment]
您好，能麻烦您说的具体一点吗 @zhangchenxu528
