### ISSUE TITLE
train3.npz

### ISSUE THREAD

**Issue by h310558606** [zhangchenxu528/FACIAL#7]
你好，可以解释一下train3.npz这个文件的意义吗？这个是对reference video 每一帧提取的face特征吗？这个文件读出来是一个N*258的数组，这个N的意义是什么呢？
这个文件如何生成，可以稍微详细的说一下吗？十分感谢。

**Comment by zhangchenxu528** [comment]
这个是用来train obama网络的GT数据，在训练时，我放在这里是因为我对head pose normalize了。所以用这个文件只是求了一下head pose的mean 和 std。并没有其他作用。N的意思是用来训练的帧数。这个文件的生成是从video进行数据处理得到的。

**Comment by h310558606** [comment]
/content/FACIAL/face2vid/checkpoints/train3/latest_net_G.pth这个模型是用obama的reference video训练的是吗？如果我改变reference video 哪些代码和模型需要更改呢？

**Comment by zhangchenxu528** [comment]
你不需要改变training 代码，改变reference video重新训练，只需要定义好你的数据路径和训练名称就可以了。
