### ISSUE TITLE
Question regarding dataset102.py

### ISSUE THREAD

**Issue by shoang22** [zhangchenxu528/FACIAL#77]
I noticed that when creating the dataset, you concatenated the frames of all the audio samples to form one tensor containing all audio frames across all samples. Wouldn't that result in temporal inconsistencies during training if a sampled window contained frames from two different videos? Or was this script designed purely for fine-tuning on one video?

**Comment by zhangchenxu528** [comment]
The dataset is designed for more than one video. We use self.dataset_idx to ensure the sample clip is only in one video every time. 
Please refer to this code: self.dataset_idx += list(np.arange(0, min_num_frame-self.frames, 1) + base)

**Comment by shoang22** [comment]
Whoops, missed that. Thanks for clarifying.
