### ISSUE TITLE
About supplementary

### ISSUE THREAD

**Issue by TaengguTae** [zhangchenxu528/FACIAL#82]
Hello, I would like to know that where to find the supplementary. 

Thank u!

**Comment by zhao1f** [comment]
Thanks for the interests, please refer to the official link for more details.
https://openaccess.thecvf.com/content/ICCV2021/html/Zhang_FACIAL_Synthesizing_Dynamic_Talking_Face_With_Implicit_Attribute_Learning_ICCV_2021_paper.html

**Comment by TaengguTae** [comment]
> Thanks for the interests, please refer to the official link for more details. https://openaccess.thecvf.com/content/ICCV2021/html/Zhang_FACIAL_Synthesizing_Dynamic_Talking_Face_With_Implicit_Attribute_Learning_ICCV_2021_paper.html

Thank u! That helps me a lot! :)
