### ISSUE TITLE
模型推理和渲染速度如何？

### ISSUE THREAD

**Issue by pineking** [zhangchenxu528/FACIAL#9]
@zhangchenxu528 

模型推理和渲染速度如何？是否有可能在终端完成实时推理和渲染

**Comment by zhangchenxu528** [comment]
你好，理论上是可以实时的，目前主要限制在于C++渲染，这部分可以使用GUP渲染代替。

**Comment by psuu0001** [comment]
> 

你好，请问渲染这部分，要怎么做才能使用GPU代替呢？
